### ISSUE TITLE
Feature : add a power present but not charging state

### ISSUE THREAD

**Issue by RaphaelRochet** [Deminder/battery-indicator-icon#19]
Hi,

I previously forked an extension that did a circular battery indicator, but yours is simply better so I will use yours now.

Yet, mine has a little feature that will show when the power is present, but the battery is not charging.
It's usefull to confirm that the power cord is plugged well.

The idle state is easy to detect, here's how I did it :
```
			this._charging = proxy.State == UPower.DeviceState.CHARGING ;
			this._idle = proxy.State == UPower.DeviceState.FULLY_CHARGED
						|| proxy.State == UPower.DeviceState.PENDING_CHARGE ;
```
(It's here https://github.com/RaphaelRochet/circular-battery-indicator)

When Idle, it simply fades the charging indicator part (not the whole icon). 

Do you think you could add this feature ?

**Comment by Deminder** [comment]
I don't think that showing a partially transparent bolt would work well.
For instance, the user might falsely interpret a faded bolt to mean that the battery is just charging slowly when in reality it is not.
I feel that the design of the circular-battery-indicator extension is better suited for this feature since the grey circle is not associated to mean charging.

For this extension a clever design is missing to indicate this "plugged-in" (idle) state as the LineageOS design (which this extension is largely based on) is not showing in-between states, either.
Moreover, the indication should work with all icon styles. This seems difficult.

[`org.freedesktop.UPower.Device.IconName` shows the same icon for `PENDING_CHARGE` and `CHARGING`](https://gitlab.freedesktop.org/upower/upower/-/blob/master/src/up-device.c#L150), but this does not seem like a good idea: 
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/52c59ac0dd7ddbe064ea4b9873492ec76e289c65
https://gitlab.freedesktop.org/upower/upower/-/issues/123

**Comment by RaphaelRochet** [comment]
All right. Was worth asking :)
Thanks for the quick answer though.
